[2024-10-31T15:46:38.098+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-31T15:40:07.557042+00:00 [queued]>
[2024-10-31T15:46:38.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-31T15:40:07.557042+00:00 [queued]>
[2024-10-31T15:46:38.100+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-31T15:46:38.104+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2024-10-31 15:40:07.557042+00:00
[2024-10-31T15:46:38.106+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2024-10-31T15:46:38.108+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'green_data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2024-10-31T15:40:07.557042+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/green_data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpob2vaxdk']
[2024-10-31T15:46:38.108+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask download_dataset_task
[2024-10-31T15:46:38.124+0000] {task_command.py:416} INFO - Running <TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-31T15:40:07.557042+00:00 [running]> on host ca61c58ec0c8
[2024-10-31T15:46:38.147+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='green_data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T15:40:07.557042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T15:40:07.557042+00:00'
[2024-10-31T15:46:38.148+0000] {logging_mixin.py:154} INFO - Requesting URL: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquet
[2024-10-31T15:46:38.148+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/green_data_ingestion_gcs_dag.py", line 43, in download_data_and_concat
    response = requests.get(url)
NameError: name 'requests' is not defined
[2024-10-31T15:46:38.151+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=green_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20241031T154007, start_date=20241031T154638, end_date=20241031T154638
[2024-10-31T15:46:38.155+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task download_dataset_task (name 'requests' is not defined; 365)
[2024-10-31T15:46:38.164+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-31T15:46:38.173+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
