[2024-10-15T21:24:44.025+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:24:42.004335+00:00 [queued]>
[2024-10-15T21:24:44.028+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:24:42.004335+00:00 [queued]>
[2024-10-15T21:24:44.028+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-15T21:24:44.033+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2024-10-15 21:24:42.004335+00:00
[2024-10-15T21:24:44.035+0000] {standard_task_runner.py:57} INFO - Started process 80 to run task
[2024-10-15T21:24:44.037+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yellow_data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2024-10-15T21:24:42.004335+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/yellow_data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpzjk9b8b8']
[2024-10-15T21:24:44.037+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask download_dataset_task
[2024-10-15T21:24:44.054+0000] {task_command.py:416} INFO - Running <TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:24:42.004335+00:00 [running]> on host 63fbd9348e70
[2024-10-15T21:24:44.083+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T21:24:42.004335+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T21:24:42.004335+00:00'
[2024-10-15T21:25:27.400+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_data_ingestion_gcs_dag.py", line 43, in download_data_and_concat
    pf = pd.read_parquet(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 368, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 270, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2024-10-15T21:25:27.409+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20241015T212442, start_date=20241015T212444, end_date=20241015T212527
[2024-10-15T21:25:27.417+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task download_dataset_task (HTTP Error 403: Forbidden; 80)
[2024-10-15T21:25:27.448+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-15T21:25:27.459+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
