[2024-10-15T21:30:53.805+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:30:53.149491+00:00 [queued]>
[2024-10-15T21:30:53.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:30:53.149491+00:00 [queued]>
[2024-10-15T21:30:53.807+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-15T21:30:53.812+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2024-10-15 21:30:53.149491+00:00
[2024-10-15T21:30:53.815+0000] {standard_task_runner.py:57} INFO - Started process 82 to run task
[2024-10-15T21:30:53.816+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yellow_data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2024-10-15T21:30:53.149491+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/yellow_data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpkw4aa61f']
[2024-10-15T21:30:53.816+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask download_dataset_task
[2024-10-15T21:30:53.832+0000] {task_command.py:416} INFO - Running <TaskInstance: yellow_data_ingestion_gcs_dag.download_dataset_task manual__2024-10-15T21:30:53.149491+00:00 [running]> on host 63fbd9348e70
[2024-10-15T21:30:53.859+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T21:30:53.149491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T21:30:53.149491+00:00'
[2024-10-15T21:30:53.861+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_data_ingestion_gcs_dag.py", line 43, in download_data_and_concat
    time.sleep(2)
NameError: name 'time' is not defined
[2024-10-15T21:30:53.864+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20241015T213053, start_date=20241015T213053, end_date=20241015T213053
[2024-10-15T21:30:53.868+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task download_dataset_task (name 'time' is not defined; 82)
[2024-10-15T21:30:53.874+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-15T21:30:53.884+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
