[2024-10-31T15:40:08.643+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-30T00:00:00+00:00 [queued]>
[2024-10-31T15:40:08.646+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-30T00:00:00+00:00 [queued]>
[2024-10-31T15:40:08.646+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-31T15:40:08.650+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2024-10-30 00:00:00+00:00
[2024-10-31T15:40:08.652+0000] {standard_task_runner.py:57} INFO - Started process 242 to run task
[2024-10-31T15:40:08.653+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'green_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2024-10-30T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/green_data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp5nylrp08']
[2024-10-31T15:40:08.654+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask download_dataset_task
[2024-10-31T15:40:08.671+0000] {task_command.py:416} INFO - Running <TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-30T00:00:00+00:00 [running]> on host ca61c58ec0c8
[2024-10-31T15:40:08.697+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='green_data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T00:00:00+00:00'
[2024-10-31T15:41:36.097+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/green_data_ingestion_gcs_dag.py", line 42, in download_data_and_concat
    pf = pd.read_parquet(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 373, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
  File "/usr/local/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1457087 bytes read, 62172 more expected)
[2024-10-31T15:41:36.107+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=green_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20241030T000000, start_date=20241031T154008, end_date=20241031T154136
[2024-10-31T15:41:36.116+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task download_dataset_task (IncompleteRead(1457087 bytes read, 62172 more expected); 242)
[2024-10-31T15:41:36.149+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-31T15:41:36.162+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
