[2024-10-10T17:36:23.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T17:36:23.292+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T17:36:23.293+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-10T17:36:23.297+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2024-10-09 00:00:00+00:00
[2024-10-10T17:36:23.300+0000] {standard_task_runner.py:57} INFO - Started process 29745 to run task
[2024-10-10T17:36:23.302+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'green_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/green_data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp43694mt1']
[2024-10-10T17:36:23.302+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask download_dataset_task
[2024-10-10T17:36:23.320+0000] {task_command.py:416} INFO - Running <TaskInstance: green_data_ingestion_gcs_dag.download_dataset_task scheduled__2024-10-09T00:00:00+00:00 [running]> on host 72e947e9fa68
[2024-10-10T17:36:23.345+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='green_data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-10T17:36:28.096+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/green_data_ingestion_gcs_dag.py", line 45, in download_data_and_concat
    pq.write_table(final_pf, f"{path_to_local_home}/{dataset_file}")
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 3072, in write_table
    where, table.schema,
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
[2024-10-10T17:36:28.103+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=green_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20241009T000000, start_date=20241010T173623, end_date=20241010T173628
[2024-10-10T17:36:28.108+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task download_dataset_task ('DataFrame' object has no attribute 'schema'; 29745)
[2024-10-10T17:36:28.141+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-10T17:36:28.152+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
